### PR TITLE
Pin fsnotify/fsevents to v0.1.1 for darwin cross-compile

### PR DESCRIPTION
**Pull request by pose**
## Summary

Pin `github.com/fsnotify/fsevents` to v0.1.1 via a `replace` directive in `provider/go.mod`. v0.2.0 cannot be cross-compiled for darwin with `CGO_ENABLED=0`.

## Why

fsevents v0.2.0 splits its API across CGO build tags: the always-compiled `fsevents.go` (darwin-tagged) references symbols (`GetDeviceUUID`, `start`, `flush`, `stop`) that are only defined in a `darwin && cgo` tagged file. The provider Makefile cross-compiles darwin with `CGO_ENABLED=0` (see `scripts/crossbuild.mk:20-23`), so the CGO file is excluded and the references fail to resolve.

This broke master on 2026-05-11 when [terraform-provider-docker v4.3.0 was merged](https://github.com/pulumi/pulumi-docker/commit/0adbd92b) (#1697). PR #1697 was green because the PR check matrix only builds linux-amd64 and windows-amd64 — there is no darwin cross-build in `run-acceptance-tests.yml`, so the regression slipped through.

`gh run list --workflow=master.yml` shows three consecutive failed master runs since #1697 merged.

## Verification

Reproduced and verified locally with `GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build`:
- Before pin: `fsevents.go:147: undefined: GetDeviceUUID` (+ 3 other undefined symbols)
- After pin: clean compile through fsevents
- A/B confirmed by toggling the `replace` line on and off

I will also trigger `master.yml` via `workflow_dispatch` on this branch to run the full darwin matrix in CI before merging.

## Follow-up

The PR check matrix in `run-acceptance-tests.yml` should be expanded to include darwin-amd64 / darwin-arm64 so a future fsevents-style regression can be caught at PR time rather than post-merge. That belongs in `pulumi/ci-mgmt` since these workflows are autogenerated.

Tracked in pulumi/ci-mgmt#2233.

Part of #1698

### CODE REVIEW

**Comment by pose** [comment]
Closing — pinning fsevents to v0.1.1 does not fix the build.

I verified this by triggering `master.yml` on this branch via `workflow_dispatch` ([run](https://github.com/pulumi/pulumi-docker/actions/runs/25862243905)). `build_provider / Build darwin-arm64` failed with the same class of CGO-undefined-symbol error against v0.1.1:

```
fsevents@v0.1.1/fsevents.go:101: undefined: FSEventStreamRef
fsevents@v0.1.1/fsevents.go:102: undefined: CFRunLoopRef
fsevents@v0.1.1/fsevents.go:161: undefined: GetDeviceUUID
fsevents@v0.1.1/fsevents.go:162: es.start undefined
fsevents@v0.1.1/fsevents.go:167: undefined: flush
fsevents@v0.1.1/fsevents.go:173: undefined: stop
```

My initial hypothesis that v0.1.x predated the CGO split was wrong — fsevents has always been CGO-only on darwin. There is no fsevents version that compiles with `CGO_ENABLED=0`.

The real root cause is that PR #1697 (upstream → v4.3.0) introduced `resource_docker_compose.go`, which transitively pulls in `docker/compose/v2/pkg/watch` → `fsnotify/fsevents`. The structural conflict is between the static cross-compile model (`CGO_ENABLED=0` from Linux) and the new upstream feature requiring CGO on darwin.

Path forward, documented in #1698:
- Short-term: a new PR using pulumi-docker's existing `patches/` system to remove `resource_docker_compose.go` from upstream until upstream supports building without compose.
- Durable: an upstream PR to `kreuzwerker/terraform-provider-docker` adding a build-tag gate on the compose resource.
- Separate: pulumi/ci-mgmt#2233 to expand the PR build matrix to include darwin so the next regression of this class fails at PR time.
